class MyException(Exception):
    """Исключение для обработки ошибок."""
    pass